# Generated by Django 5.2 on 2025-05-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_roomtable_created_at_roomtable_passowrd_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtable',
            name='Password',
            field=models.CharField(default='IloveAce', max_length=100),
        ),
    ]
