# Generated by Django 5.2 on 2025-05-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_roomtable_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtable',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='roomtable',
            old_name='Room_id',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='roomtable',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='roomtable',
            name='Password',
        ),
        migrations.AddField(
            model_name='roomtable',
            name='password',
            field=models.CharField(default='ILOVEACE', max_length=100),
        ),
    ]
