# Generated by Django 5.2.6 on 2025-10-09 16:52

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('selected_game', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('players_connected_list', models.JSONField(default=dict)),
                ('players_card_list', models.JSONField(default=dict)),
                ('played_card_list', models.JSONField(default=list)),
                ('game_completed_players_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('starting_player', models.CharField(max_length=100)),
                ('current_player', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('card_distributed_flag', models.BooleanField(default=False)),
                ('duplicate_owner_login', models.BooleanField(default=False)),
                ('card_problem', models.JSONField(default=dict)),
                ('current_round', models.JSONField(default=dict)),
                ('cardList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('gamelist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('number_of_games_played', models.IntegerField(default=0)),
                ('number_of_games_won', models.IntegerField(default=0)),
            ],
        ),
    ]
