# Generated by Django 5.2.6 on 2025-10-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_completedgame_playerstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedgame',
            old_name='game_id',
            new_name='room_id',
        ),
    ]
