# Generated by Django 5.2.6 on 2025-10-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_game_id_completedgame_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedgame',
            name='room_id',
            field=models.CharField(max_length=100),
        ),
    ]
