# Generated by Django 5.2.6 on 2025-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_completedgame_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='number_of_games_lost',
            field=models.IntegerField(default=0),
        ),
    ]
